# Singular Value Decomposition (SVD)

## Pendahuluan

**Singular Value Decomposition (SVD)** merupakan salah satu teknik faktorisasi matriks yang sangat penting dalam aljabar linear. Metode ini menguraikan sebuah matriks menjadi beberapa komponen yang lebih sederhana sehingga karakteristik utama matriks dapat dipahami dengan lebih mudah.

SVD banyak dimanfaatkan dalam berbagai bidang, antara lain:

- Pemrosesan sinyal (*signal processing*)
- Kompresi citra (*image compression*)
- Reduksi dimensi pada *machine learning*
- Sistem rekomendasi
- Analisis data dan *data mining*

Untuk memahami SVD, diperlukan pengetahuan dasar mengenai:

- Operasi matriks dan vektor
- Rank matriks
- Nilai eigen dan vektor eigen
- Matriks ortogonal
- Transformasi linear

---

## Definisi Matematis

Untuk suatu matriks riil $A$ berukuran $m \times n$, dekomposisi SVD dinyatakan sebagai:

$$
A = U \Sigma V^T
$$

dengan:

### 1. Matriks $U$

Matriks $U$ merupakan matriks ortogonal berukuran $m \times m$.

Sifat pentingnya adalah:

$$
U^T U = U U^T = I
$$

Kolom-kolom pada matriks $U$ disebut **vektor singular kiri** (*left singular vectors*) dari matriks $A$.

---

### 2. Matriks $\Sigma$

Matriks $\Sigma$ merupakan matriks diagonal berukuran $m \times n$ yang memuat nilai-nilai singular (*singular values*) pada diagonal utamanya.

Bentuk umumnya adalah:

$$
\Sigma =
\begin{bmatrix}
\sigma_1 & 0 & \cdots & 0 \\
0 & \sigma_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \sigma_r
\end{bmatrix}
$$

dengan:

$$
\sigma_1 \ge \sigma_2 \ge \cdots \ge \sigma_r \ge 0
$$

di mana:

- $\sigma_i$ disebut nilai singular (*singular value*).
- Semua nilai singular selalu bernilai tidak negatif.
- Banyaknya nilai singular yang tidak nol sama dengan rank matriks $A$.

Nilai singular menunjukkan besarnya kontribusi setiap arah utama dalam merepresentasikan data.

---

### 3. Matriks $V^T$

Matriks $V^T$ merupakan transpose dari matriks ortogonal $V$ yang berukuran $n \times n$.

Sifat ortogonalnya diberikan oleh:

$$
V^T V = V V^T = I
$$

Kolom-kolom matriks $V$ disebut **vektor singular kanan** (*right singular vectors*) dari matriks $A$.

---

## Interpretasi Geometris SVD

Secara geometris, SVD dapat dipandang sebagai rangkaian tiga transformasi linear:

1. Matriks $V^T$ melakukan rotasi atau refleksi terhadap data.
2. Matriks $\Sigma$ melakukan penskalaan (*scaling*) pada setiap arah utama berdasarkan nilai singular.
3. Matriks $U$ melakukan rotasi atau refleksi kembali pada hasil transformasi sebelumnya.

Dengan demikian, transformasi yang dilakukan oleh matriks $A$ dapat dipahami sebagai kombinasi dari rotasi, penskalaan, dan rotasi kembali.

---

## Makna Nilai Singular

Nilai singular memberikan informasi mengenai pentingnya setiap komponen dalam suatu matriks.

Beberapa interpretasi pentingnya adalah:

- Nilai singular yang besar menunjukkan arah yang memiliki kontribusi dominan.
- Nilai singular yang kecil menunjukkan arah yang kontribusinya relatif rendah.
- Nilai singular yang mendekati nol sering kali dapat diabaikan untuk memperoleh representasi yang lebih sederhana tanpa kehilangan banyak informasi.

Konsep ini menjadi dasar dalam teknik kompresi data dan reduksi dimensi.

---

## Aplikasi SVD

### 1. Kompresi Citra

SVD memungkinkan gambar direpresentasikan menggunakan sejumlah kecil nilai singular terbesar sehingga ukuran penyimpanan dapat dikurangi tanpa menghilangkan kualitas secara signifikan.

### 2. Reduksi Dimensi

Dalam analisis data dan *machine learning*, SVD digunakan untuk mengurangi jumlah fitur sambil mempertahankan informasi utama yang terkandung dalam data.

### 3. Sistem Rekomendasi

Banyak sistem rekomendasi memanfaatkan SVD untuk menemukan pola preferensi pengguna dan memberikan rekomendasi yang lebih akurat.

### 4. Analisis Data

SVD membantu mengidentifikasi struktur tersembunyi dalam data serta mengurangi pengaruh *noise*.

---

## Kesimpulan

Singular Value Decomposition (SVD) merupakan metode faktorisasi matriks yang menguraikan suatu matriks menjadi tiga komponen utama:

$$
A = U \Sigma V^T
$$

di mana:

- $U$ berisi vektor singular kiri.
- $\Sigma$ berisi nilai singular.
- $V^T$ berisi vektor singular kanan.

Melalui dekomposisi ini, struktur suatu matriks dapat dianalisis dengan lebih mudah. Oleh karena itu, SVD menjadi salah satu teknik fundamental dalam aljabar linear modern, analisis data, kompresi citra, serta berbagai aplikasi *machine learning*.

In [3]:
import numpy as np

A = np.array([
    [1, 1, 0],
    [2, 1, 1],
    [1, 0, 3]
])

# Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

print("Matrix U:")
print(U)

print("\nSingular Values:")
print(S)

print("\nMatrix V^T:")
print(VT)

# Ubah S menjadi matriks diagonal Sigma
Sigma = np.diag(S)

print("\nMatrix Sigma:")
print(Sigma)

# Rekonstruksi A
hasil = U @ Sigma @ VT

print("\nHasil U @ Sigma @ V^T:")
print(np.round(hasil, 10))

Matrix U:
[[-0.21132487 -0.57735027 -0.78867513]
 [-0.57735027 -0.57735027  0.57735027]
 [-0.78867513  0.57735027 -0.21132487]]

Singular Values:
[3.73205081 2.         0.26794919]

Matrix V^T:
[[-0.57735027 -0.21132487 -0.78867513]
 [-0.57735027 -0.57735027  0.57735027]
 [ 0.57735027 -0.78867513 -0.21132487]]

Matrix Sigma:
[[3.73205081 0.         0.        ]
 [0.         2.         0.        ]
 [0.         0.         0.26794919]]

Hasil U @ Sigma @ V^T:
[[ 1.  1.  0.]
 [ 2.  1.  1.]
 [ 1. -0.  3.]]
